language: java

jdk:
- openjdk11

if: NOT commit_message =~ ^\[Tycho\].*$
install: "/bin/true"

jobs:
  include:
  - script: xvfb-run ./mvnw --settings ./.travis/settings.xml clean verify $(if [[ $TRAVIS_TAG =~ ^v.* ]]; then echo "-Prelease-composite"; fi) -B
    after_success:
    - bash <(curl -s https://codecov.io/bash)
    before_deploy:
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export project_version=v$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
    deploy:
      provider: releases
      api_key:
        secure: kY/S2FMjxtHiOHfRa9CaDP5W8WN95Z4otM5f9WInh0ePUJ7DGzo1LuAMMfVCReZR+gyFrVtTYdpk6DduPNLqCGorPp//gxAXUmYX60Q2+hsp5aQl/2HCxfnK7v3k6moQ6sCKRoyqyo4tjLTkQhYnZxL203weQKIMzt/z/RDnH8XPXY9gkPRm8wbj97u55ezk26NIdZFaPdW9PnwTc2NhddfFEefk6rbGhFclNOvMrbCo08ZqYkhhmS/itGX23kXv/O7IpgQ6jCFBezqeebIcLocVjPGnmmTwh0kWA022DSgFUvw0Nh5rc+gV0mLAA7a+ixGb3QgIRZRS3KZ2DIfmqyRZhDO3c+AdetJA/OctpRrwLb7KJBJpWzlhnnHUDcDPRIjwqvpG8tONFdLqnxXbtlDzu3SN/5fLnx2gPuj3pWuYBHUOnCRYNQ10a+aLZ+NblYKOII5ZP/Yu39jX06CeYr/eJH7rz8DsZQOcn7ZkjWEiR6X0/d+SL2D3SC3pcp8pxoGX+gl7BqfhbHuRyRsD3Oa3DFtFclVpDuewj6M0z6DnRAn0CxdjEdQD5jJo8sLJKjQdVOIcX2iPqGXeXeHtiVJnK4XB4CXpN3vMqMwwBBZUZTMQvrjlArUYoJGtmvrLZiju8eRbmpssPxgR03q3XjTMkPVpNjDpOHJcjM2bcRc=
      file_glob: true
      file:
      - "./**/target/*.jar"
      - org.contextmapper.dsl.repository/target/org.contextmapper.dsl.repository-*.zip
      skip_cleanup: true
      on:
        tags: true
      name: "$project_version"
  - script: ./gradlew clean build $(if [[ $TRAVIS_TAG =~ ^v.* || ($TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == 'false') ]]; then echo "publish -Psigning.keyId=${GPG_KEY_ID} -Psigning.password=${GPG_KEY_PASSPHRASE}"; fi)

before_install:
- sudo apt-get -y install graphviz
- openssl aes-256-cbc -K $encrypted_324cf7253e32_key -iv $encrypted_324cf7253e32_iv
  -in secret-key.gpg.enc -out secret-key.gpg -d

